name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  unit-tests:
    runs-on: self-hosted
    defaults:
      run:
        working-directory: app

    steps:
    - name: Run python docker
      uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        architecture: 'x64'
        cache: pip
    - run: pip install -r requirements.txt
  deploy:
    needs: unit-tests
    runs-on: self-hosted
    defaults:
      run:
        working-directory: app

    steps:
    - run: docker build -t test-python-git .